
[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_src_filter = +<main.cpp>

build_flags =
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.1.0
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    claws/BH1750 @ ^1.3.0
    olikraus/U8g2 @ ^2.35.19

[env:splash]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_src_filter = +<splash.cpp>

lib_deps =
    olikraus/U8g2 @ ^2.35.19

[env:sanity]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_src_filter = +<sanity.cpp>

lib_deps =
    olikraus/U8g2 @ ^2.35.19
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    claws/BH1750 @ ^1.3.0

[env:bme-test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_src_filter = +<bme-test.cpp>

lib_deps =
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14

[env:bme-bh1750-test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_src_filter = +<bme-bh1750-test.cpp>

lib_deps =
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    claws/BH1750 @ ^1.3.0

